on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.17.3
    - name: Installing dependencies
      run: npm i
    - name: Running lint
      run: npm run lint
    - name: Running unit tests
      run: npm run test
